<a href="https://colab.research.google.com/github/shreydan/ML-practice/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***PYTORCH***

- [tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)


In [1]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [2]:
x = torch.tensor([[1,2],[3,4]])
rx, cx = x.shape # or x.size()
rx,cx

(2, 2)

In [3]:
ol = torch.ones_like(x)
print(ol, ol.dtype)

tensor([[1, 1],
        [1, 1]]) torch.int64


In [4]:
rl = torch.rand_like(x, dtype=torch.float) # gotta mention dtype
rl

tensor([[0.0727, 0.1420],
        [0.1377, 0.2730]])

In [5]:
# in numpy you pass shape= in torch its size=
print(torch.ones(size=(3,4)))

rand_vals = torch.rand(size=(8,1))
print(rand_vals, rand_vals.shape)

# (8,1): matrix, (8,): vector

print(torch.zeros(size=(5,)))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.6005],
        [0.9347],
        [0.0226],
        [0.8921],
        [0.6963],
        [0.6130],
        [0.7409],
        [0.4333]]) torch.Size([8, 1])
tensor([0., 0., 0., 0., 0.])


In [6]:
# indexing, slicing -- same as numpy

t = torch.rand(size=(4,3))
print(t)
print(t[3]) # row 4 of 0,1,2,3
# print(t[4]) error duh
print(t[:,1]) # col 1 of 0,1,2

tensor([[0.1941, 0.9173, 0.8815],
        [0.0615, 0.4072, 0.6035],
        [0.6153, 0.8896, 0.4834],
        [0.9928, 0.1606, 0.6645]])
tensor([0.9928, 0.1606, 0.6645])
tensor([0.9173, 0.4072, 0.8896, 0.1606])


todo

- cat
- stack

In [22]:
# joining - cat

t1 = torch.rand((2,3))
t2 = torch.rand((2,3))
t3 = torch.rand((2,3))

# wouldnt work, sizes should match
t4 = torch.rand((3,2))

# concats by rows
t_cat = torch.cat([t1,t2,t3])

# concats by cols
t_cat_d1 = torch.cat([t1,t2,t3], dim=1)

# .cat default dim = 0

t_stack_d0 = torch.stack([t1,t2,t3])
t_stack_d1 = torch.stack([t1,t2,t3], dim=1)

print(t1, '\n', t1.shape, '\n')
print(t2, '\n', t2.shape, '\n')
print(t3, '\n', t3.shape, '\n')

print("\nCAT\n")
print(t_cat, '\n', t_cat.shape, '\n')
print(t_cat_d1, '\n', t_cat_d1.shape, '\n')

print("\nSTACK\n")
print(t_stack_d0, '\n', t_stack_d0.shape, '\n')
print(t_stack_d1, '\n', t_stack_d1.shape, '\n')

tensor([[0.3840, 0.9724, 0.3782],
        [0.7397, 0.8844, 0.2944]]) 
 torch.Size([2, 3]) 

tensor([[0.5219, 0.4519, 0.0628],
        [0.7239, 0.0745, 0.1342]]) 
 torch.Size([2, 3]) 

tensor([[0.4060, 0.5716, 0.4560],
        [0.0442, 0.5191, 0.5442]]) 
 torch.Size([2, 3]) 


CAT

tensor([[0.3840, 0.9724, 0.3782],
        [0.7397, 0.8844, 0.2944],
        [0.5219, 0.4519, 0.0628],
        [0.7239, 0.0745, 0.1342],
        [0.4060, 0.5716, 0.4560],
        [0.0442, 0.5191, 0.5442]]) 
 torch.Size([6, 3]) 

tensor([[0.3840, 0.9724, 0.3782, 0.5219, 0.4519, 0.0628, 0.4060, 0.5716, 0.4560],
        [0.7397, 0.8844, 0.2944, 0.7239, 0.0745, 0.1342, 0.0442, 0.5191, 0.5442]]) 
 torch.Size([2, 9]) 


STACK

tensor([[[0.3840, 0.9724, 0.3782],
         [0.7397, 0.8844, 0.2944]],

        [[0.5219, 0.4519, 0.0628],
         [0.7239, 0.0745, 0.1342]],

        [[0.4060, 0.5716, 0.4560],
         [0.0442, 0.5191, 0.5442]]]) 
 torch.Size([3, 2, 3]) 

tensor([[[0.3840, 0.9724, 0.3782],
         [0.5219,

#### arithmetic operations

In [28]:
t1 = torch.ones((2,2))
t2 = torch.ones((2,2))

# matmul: DOT
print(torch.matmul(t1,t2)) # method 1
print(t1 @ t2) # method 2


# * : element-wise matmul
print(torch.mul(t1,t2)) # method 1
print(t1 * t2) # method 2


# sum
print(t1+t2)
# NOTE: torch.sum() returns sum of elements

# item, returns python float
print((t1+t2).sum().item())

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
8.0


In [36]:
# in_place operations:

t = torch.rand((3,4))
print(t.t()) # does transpose or t.T
print(t) # but .t() doesn't modify t

# adding _ suffix changes operand i.e. t
print(t.t_())
print(t)

tensor([[0.6085, 0.9721, 0.6715],
        [0.2306, 0.7136, 0.7996],
        [0.1375, 0.5520, 0.6026],
        [0.9126, 0.9229, 0.3367]])
tensor([[0.6085, 0.2306, 0.1375, 0.9126],
        [0.9721, 0.7136, 0.5520, 0.9229],
        [0.6715, 0.7996, 0.6026, 0.3367]])
tensor([[0.6085, 0.9721, 0.6715],
        [0.2306, 0.7136, 0.7996],
        [0.1375, 0.5520, 0.6026],
        [0.9126, 0.9229, 0.3367]])
tensor([[0.6085, 0.9721, 0.6715],
        [0.2306, 0.7136, 0.7996],
        [0.1375, 0.5520, 0.6026],
        [0.9126, 0.9229, 0.3367]])


numpy to tensor:

t = torch.from_numpy(n)

tensor to numpy:

n = torch.numpy()